print("(Loaded) Developer Custom Fish Generator")

local ROLE_DEVELOPER = 51

-- Helper to apply style to dialogs
local function applyStyle(player)
    if player.setNextDialogRGBA       then player:setNextDialogRGBA(10, 10, 20, 254)        end
    if player.setNextDialogBorderRGBA then player:setNextDialogBorderRGBA(0, 200, 120, 255) end
end

local function resetStyle(player)
    if player.resetDialogColor then player:resetDialogColor() end
end

-- Command Registration
registerLuaCommand({
    command      = "fishmaker",
    roleRequired = ROLE_DEVELOPER,
    description  = "Open the Developer Custom Fish Generator UI"
})

-- Show the UI
local function showFishMakerUI(player)
    applyStyle(player)
    local d = {}
    
    table.insert(d, "set_default_color|`o")
    table.insert(d, "add_label_with_icon|big|`wCustom Fish Generator``|left|802|")
    table.insert(d, "add_smalltext|`oGenerate multiple custom fish combinations at once!|left|")
    table.insert(d, "add_spacer|small|")
    
    table.insert(d, "add_text_input|base_id|Base Fish Item ID:|4320|5|")
    table.insert(d, "add_smalltext|`o(The existing item whose asset/texture you want to copy, e.g., 4320 for Bass)|left|")
    table.insert(d, "add_spacer|small|")
    
    table.insert(d, "add_text_input|base_name|Base Name:|Kraken|30|")
    table.insert(d, "add_smalltext|`o(e.g., Kraken)|left|")
    table.insert(d, "add_spacer|small|")
    
    table.insert(d, "add_text_input|prefixes|Prefixes (comma separated):|Diamond, Mutated, Rainbow|60|")
    table.insert(d, "add_smalltext|`o(Leave empty if none. Combinations will be auto-generated)|left|")
    table.insert(d, "add_spacer|small|")
    
    table.insert(d, "add_text_input|start_id|Starting Target ID:|25010|10|")
    table.insert(d, "add_smalltext|`o(The system will find safe empty IDs starting from here)|left|")
    table.insert(d, "add_spacer|small|")
    
    table.insert(d, "end_dialog|fishmaker_submit|Cancel|Generate!|\nadd_quick_exit|")
    
    player:onDialogRequest(table.concat(d, "\n"))
    resetStyle(player)
end

onPlayerCommandCallback(function(world, player, fullCommand)
    local cmd = fullCommand:match("^(%S+)")
    if not cmd or cmd:lower() ~= "fishmaker" then return false end

    if not player:hasRole(ROLE_DEVELOPER) then
        player:onConsoleMessage("`4Access Denied: `o/fishmaker requires Developer role.``")
        return true
    end

    showFishMakerUI(player)
    return true
end)

-- Helper: Get all combinations of an array (Powerset)
local function getCombinations(arr)
    local results = {{}}
    for i = 1, #arr do
        local el = arr[i]
        local currentLen = #results
        for j = 1, currentLen do
            local newCombo = {}
            for k = 1, #results[j] do
                table.insert(newCombo, results[j][k])
            end
            table.insert(newCombo, el)
            table.insert(results, newCombo)
        end
    end
    return results
end

-- Helper: Check if ID is empty/safe
local function isSafeID(id)
    local itm = getItem(id)
    if not itm then return true end
    local name = itm:getName()
    if not name or name == "" or name == "Blank" or name:sub(1, 5) == "item_" or name:sub(1, 7) == "Seed..." then
        return true
    end
    return false
end

-- Handle Dialog Submit
onPlayerDialogCallback(function(world, player, data)
    if data["dialog_name"] == "portal_shortcuts" and data["buttonClicked"] == "sc_fishmaker" then
        if player:hasRole(51) then showFishMakerUI(player) end
        return true
    end

    if data["dialog_name"] ~= "fishmaker_submit" then return false end
    if data["buttonClicked"] ~= "1" then return true end -- Cancelled

    local base_id = tonumber(data["base_id"]) or 0
    local base_name = data["base_name"] or ""
    local prefixes_str = data["prefixes"] or ""
    local start_id = tonumber(data["start_id"]) or 25010
    
    if base_id <= 0 or base_name == "" then
        player:onConsoleMessage("`4Error: Invalid Base ID or Name.``")
        return true
    end

    local baseItem = getItem(base_id)
    if not baseItem then
        player:onConsoleMessage("`4Error: Base item ID " .. base_id .. " does not exist.``")
        return true
    end

    -- Parse prefixes
    local prefixes = {}
    for p in prefixes_str:gmatch("[^,]+") do
        local trimmed = p:match("^%s*(.-)%s*$")
        if trimmed and trimmed ~= "" then
            table.insert(prefixes, trimmed)
        end
    end

    -- Generate combinations
    local combos = getCombinations(prefixes)
    
    -- Generate Lua output block
    local luaBlock = "\n-- Auto-Generated by /fishmaker at " .. os.date("%c") .. "\n"
    luaBlock = luaBlock .. "-- Base: " .. base_name .. " (Asset: " .. base_id .. ")\n"
    luaBlock = luaBlock .. "do\n"
    luaBlock = luaBlock .. "    local function applyFish(id, name, baseID)\n"
    luaBlock = luaBlock .. "        local src = getItem(baseID)\n"
    luaBlock = luaBlock .. "        local tgt = getItem(id)\n"
    luaBlock = luaBlock .. "        if not src or not tgt then return end\n"
    luaBlock = luaBlock .. "        tgt:setName(name)\n"
    luaBlock = luaBlock .. "        tgt:setTexture(src:getTexture())\n"
    luaBlock = luaBlock .. "        tgt:setTextureX(src:getTextureX())\n"
    luaBlock = luaBlock .. "        tgt:setTextureY(src:getTextureY())\n"
    luaBlock = luaBlock .. "        tgt:setTextureHash(src:getTextureHash())\n"
    luaBlock = luaBlock .. "        tgt:setCategoryType(src:getCategoryType())\n"
    luaBlock = luaBlock .. "        tgt:setActionType(src:getActionType())\n"
    luaBlock = luaBlock .. "        tgt:setClothingType(src:getClothingType())\n"
    luaBlock = luaBlock .. "    end\n\n"
    
    local current_id = start_id
    local generatedCount = 0
    
    for _, combo in ipairs(combos) do
        -- Build the full name
        local fullName = ""
        if #combo > 0 then
            fullName = table.concat(combo, " ") .. " " .. base_name
        else
            fullName = base_name
        end
        
        -- Find next safe ID
        while not isSafeID(current_id) do
            current_id = current_id + 1
            if current_id > 30000 then -- Failsafe
                player:onConsoleMessage("`4Error: Exceeded maximum item ID search.``")
                return true
            end
        end
        
        -- Apply to active memory right now so developer sees it instantly without restart
        local tgt = getItem(current_id)
        if tgt then
            tgt:setName(fullName)
            tgt:setTexture(baseItem:getTexture())
            tgt:setTextureX(baseItem:getTextureX())
            tgt:setTextureY(baseItem:getTextureY())
            tgt:setTextureHash(baseItem:getTextureHash())
            tgt:setCategoryType(baseItem:getCategoryType())
            tgt:setActionType(baseItem:getActionType())
            tgt:setClothingType(baseItem:getClothingType())
        end
        
        -- Append to Lua block for persistence
        luaBlock = luaBlock .. string.format("    applyFish(%d, %q, %d)\n", current_id, fullName, base_id)
        
        player:onConsoleMessage("`2>> Generated: `w" .. fullName .. " `o(ID: " .. current_id .. ")``")
        
        current_id = current_id + 1
        generatedCount = generatedCount + 1
    end
    
    luaBlock = luaBlock .. "end\n"
    
    -- Try to save to custom-fish-data.lua
    local f, err = io.open("custom-fish-data.lua", "a")
    if f then
        f:write(luaBlock)
        f:close()
        player:onConsoleMessage("`9Success! `oSaved `w" .. generatedCount .. "`o combinations to custom-fish-data.lua.``")
    else
        player:onConsoleMessage("`4Warning: `oCould not save to file (io.open failed: " .. tostring(err) .. "). Items applied to memory only.``")
    end

    player:onTalkBubble(player:getNetID(), "`2Generated " .. generatedCount .. " fishes!``", 0)
    return true
end)
